name: CI/CD Pipeline

on:
 push:
   branches: [ main ]

jobs:
 build:
   runs-on: ubuntu-latest

   steps:
   - uses: actions/checkout@v2

   - name: Build Docker Images
     run: |
       cd backend && docker build -t my-backend .
       cd ../database && docker build -t my-database .

   - name: Deploy to Kubernetes
     run: echo "Deploy your application here"